import Database from 'better-sqlite3'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import { migrate } from 'drizzle-orm/better-sqlite3/migrator'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { DATA_DIR } from '../env.js'
import * as schema from './schema.js'

const DB_PATH = path.join(DATA_DIR, 'coach.db')
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true })

const sqlite = new Database(DB_PATH)
sqlite.pragma('journal_mode = WAL')
sqlite.pragma('foreign_keys = ON')
sqlite.pragma('busy_timeout = 5000')

export const db = drizzle(sqlite, { schema })
export { sqlite }

// Run committed SQL migrations at boot (drizzle/ folder, generated by
// `npx drizzle-kit generate`). Idempotent — applied migrations are tracked.
const SERVER_DIR = path.dirname(fileURLToPath(import.meta.url))
const MIGRATIONS_DIR = path.resolve(SERVER_DIR, '..', '..', 'drizzle')

export function runMigrations() {
  migrate(db, { migrationsFolder: MIGRATIONS_DIR })
  console.log('[db] migrations applied · db at', DB_PATH)
}
